travis:
  secure:
    BINSTAR_TOKEN: wftGT+d/G7FzhelYFbOwDeU3gL2ZqALobUjHmf4YpY1YL+vZRSnrVODGB/qxp27VGoKedvxSx/gY8s6dcWjDwFI0nUVNfafq8Fkge0MvF+QWrKIwYFdkIs7GGu1YIkU0S/2Grt+FB1ZLuuTqHB6ZLz8DdCEyqFXDB3WxerZApRO+H+WiEZko9oyrG6jMIoywndsWR4E0Vx7O+gpsv/Z6WZmi8LMDR3Sg8CPO2niIWB+92VhW3Ppz1yPRftRYowg7MKNUrvM79Pcbr12lXHmfvou3VLwo6fe2a4bw5N3MMn8scCgcXk+UDHlPcAdoTgDPqTdimfKCD1SAlVfWMaZsBy+UrLZCmhG589F9ZPJ7s7/8kMrz8o1WCptbsDeK1Hk+H99BWLVOB1q7BzaXZwCkUpOxNDAv8wSrjNGYZiHluwwitGTCc48U+flgeYJpnW50+WoU8rCmvP8vQtKuxuLufHg/MMA6nH74UQeUcA7Eb8dy/NIiDrCjuxARMB9Gr0scyPJK+yMeakSSrEf8ZllHDNu6ZlDu5j0Q94RXSuqXkSeGTJWQ1+HrGqj8T8ijYhAxpiMgaypljKbKKaIR61drNjmt4Trf40AffRs6fGjzi8AhnlnGEDp6AtMANe2zpdHTKCxbf8Vk+czw5oUSAxFYa+BXLnegzivH/sIjjW5COZI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: false
