appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: htqe+juysbrMVqzussHewA9XATg4xvS7NuWjUqnh5EtwypOuQOLttpE5mO2KdokOEfZlNXjC/FkeZrldewmoBLwwpYIF10wIRU9Aduvf2PPxHZbQMYT3L/b32yWDZQUiVoFHIiYCVW2HIzAq7dRgbxprQ+Gcj1H6X1fhRXaUwDaMAkGq2gM4mJagdNtZlGl0CpM/p6ZAipJ68krkMw5tqHd6DBwdxe3WbvqrZMmWO5GDWVhix1WvVNnUxA8/BotyOHIGqlH9+wm8ofmaZvInFnd0kUYWZGgrTZCY3pGc4EfVNA2621Mdn3fd3UtyVBYxA1mBzv/Z4HHzD52k6qxGI6hSnab9qLWGC+mqDjyX6jWmZRZsXhuIyCJHrRgGOmeis9kP5jzzYoX4mPxrEh2nNFNOWHCsCM/N/BQamvRNnuD/6weXoVf/getDpHoZB9+EAQb2RjhIIq3aaJhPu6iO/pL7pjyKl4IyHOPLUQ6HYvqD1ONaBpKaqUbWKtT+bSBKEchWOSuAzKBy1i9WdcV5kQzDyFNlKc/S+Y0yDjn7gQnh/7BUYU2ILFh1PLVPIU43WT2nIrtS/kX4kzSpYAN8kM8ZFU3NXLakxo2wOoEZdV5QgN6NaAC7YdWUd9NT/OnYtDY1kl6BzOPO3QQzUi7YcKJwKPGy2ATobU7Eu5GYx4g=}
conda_forge_output_validation: false
