travis:
  secure:
    BINSTAR_TOKEN: lf4VIu9TTJV06vG5mSV5GEebLpBTQSkfIyG9UO2zumjTL4Tq75akaXG0G8Ij+r0Ho3BFnvlj1XFUMBjfKA5wRjnAb+vO7klWqjQDRwqEG+Omg8kDo+YrzMMLC7aaE5FSEyfCT4yxXX+3Ey8M/5cVwoYpxcY4/xBlGbkAOqpqRDzd8IJOFhJDsVABPhmM3Yr9wtYOMUSKV4fS50UOlK+GTa/e0BIo2103OkBIoV/YSuRKeVlOqPndR3hAWJedUMh6Uz4oAV0q+EI4LgTlyqcVfiZxCVfSPBVA53G2OMYLab26C8C1cdAKUG7rMLwtul9JXUt3hGuELtzt5hTY0OhPGYgfsUQufhA+OStI+ylsiaIWqk53WDeB2MB1NJadl05f2UxhgQzqLVIOSOeDBUbd2oRTo/tAuSqcwMN35CSeKnCRvvdb9L9YTTIDLmXDwdcOoRtO4oXl1ie5P1ONNwA3ws3NK6rJPYbOEjl0iknVTFv7UcerSxVRvM9I7rG11/COm+xvPw+n3qOTqPH8uRtOP66CNIa4Uzfrr6wmiT2sTNzgb9DAPzyB6O/xO+JQMqHgIYYSgQhj/G66sylBAXsO7mPwryV0fmJ5OX0c7E17FRxbtMI3PBPw+LsUhQM2g04/svopALF+QNn0RLSiUEJqmHpBZnlxds55yXsVpAukilY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
